### ISSUE TITLE
When I keep clicking on Upvotes, there will be an issue of repeated voting, and even negative numbers may appear.

### ISSUE THREAD

**Issue by thejoven** [chroxify/feedbase#50]
https://hub.feedbase.app/feedback

**Comment by thejoven** [comment]
<img width="1163" alt="image" src="https://github.com/user-attachments/assets/0a2e31f8-9374-4e78-ab3e-54ea77f11e0a">

**Comment by chroxify** [comment]
Hey, thanks for the feedback!
This issue is fixed in the v1.0.0 release already, therefore I'll close this Issue.
You can keep track of it's state here: #46
